INSERT INTO category (description) VALUES ( 'American' );
INSERT INTO category (description) VALUES ( 'Italian' );
INSERT INTO category (description) VALUES ( 'Mexican' );
INSERT INTO category (description) VALUES ( 'Chinese' );
INSERT INTO  unit_of_measure (description) VALUES ( 'Teaspoon' );
INSERT INTO  unit_of_measure (description) VALUES ( 'Tablespoon' );
INSERT INTO  unit_of_measure (description) VALUES ( 'Cut' );
INSERT INTO  unit_of_measure (description) VALUES ( 'Pinch' );
INSERT INTO  unit_of_measure (description) VALUES ( 'Ounce' );
